def HP15():
    print("Main Specs:")
    print("Processor: 7th Gen Intel Core i3-7100U processor, 2.4GHz base processor speed, 2 cores, 3MB cache.")
    print("Operating System: Pre-loaded Windows 10 Home with lifetime validity")
    print("Display: 15.6-inch Full HD (1920x1080) WLED display, Display Features: Diagonal FHD SVA Anti-Glare WLED-backlit Display")
    print("Memory & Storage: 4GB DDR4 RAM Intel HD Graphics 620 | Storage: 1TB HDD, HDD Speed(RPM): 5400 RPM")
    print("Design & battery: Multi-touch gesture support | Thin and light design | Laptop weight: 2.2 kg | Average battery life = 7 hours, HP Fast Charge battery, Battery: 3 Cell, Li-Ion, Power Supply: 41 W AC Adapter W")
    print("Warranty: This genuine HP laptop comes with a 1-year domestic warranty from HP covering manufacturing defects and not covering physical damage. For more details, see Warranty section below")
    print("Preinstalled Software: Windows 10 Home | In the Box: Laptop with included battery and charger Ports & CD drive: 1 HDMI, 2 USB 3.0, 1 USB 2.0, 1 Audio-output | With CD drive Other features: Anti Glare Display")
    
    

    Details = input("Type more for further details: ")
    if Details == "More" or Details == "more":
        print("Brand	HP")
        print("Model	DA0326TU")
        print("Model Name	15")
        print("Model Year	2018")
        print("Item Weight	2.04 Kg")
        print("Product Dimensions	37.6 x 24.6 x 2.3 cm")
        print("Batteries:	1 Lithium Polymer batteries required. (included)")
        print("Item model number	DA0326TU")
        print("RAM Size	4 GB")
        print("Memory Storage Capacity	4 GB")
        print("Memory Slots Available	2")
        print("Ram Memory Installed Size	4 GB")
        print("Ram Memory Maximum Size	16 GB")
        print("Ram Memory Technology	DDR4")
        print("Computer Memory Type	GDDR4")
        print("Hard Drive Size	1024 GB")
        print("Hard Drive Interface	Serial ATA")
        print("Hard Disk Rotational Speed	5400 RPM")
        print("Hard Disk Technology	Mechanical Hard Drive")
        print("Optical Drive Type	DVD+RW")
        print("Operating System	Windows 10 Home")
        print("Processor Brand	Intel")
        print("Processor Speed	2.40 GHz")
        print("Processor Type	Core i3 7100U")
        print("Processor Count	2")
        print("Hardware Platform	PC")
        print("System Bus Speed	800 MHz")
        print("Graphics Coprocessor	Intel HD Graphics")
        print("Additional Features	anti reflective, cd/dvd")
        print("Included Components	Laptop, Battery, AC Adapter, User Guide and Manuals")
        print("Software Included	Preinstalled Software: Windows 10 Home")
        print("Notebook Display Technology	LED")
        print("Screen Size	15.6 Inches")
        print("Display Type	LED-Backlit")
        print("Image Brightness	220 nits")
        print("Aspect Ratio	16:9")
        print("Display Resolution Maximum	1920 x 1080 (Full HD)")
        print("Audio Output Type	Headphones")
        print("Battery Average Life	7 Hours")
        print("Batteries Included	Yes")
        print("Batteries Required	Yes")
        print("Battery Cell Composition	Lithium Ion")
        print("Wireless Type	802.11bgn")
        print("Speaker Output Channel Quantity	2")
        print("Total Usb Ports	1")
        print("Connector Type	Wireless")
        print("Device interface - primary	Touch Pad")
        print("Supports Bluetooth Technology	Yes")
        print()
        print("                    Price: Rs.29,490                    ")
    
    final = input("Buy           Add to Cart          Back")
    if final == "Buy" or final == "buy" or final == "1" :
        print("Item Purchased")
        print("Returning to Home Screen")
        
    elif final == "Add" or final == "add" or final == "2":
        f = open("Cart", "w")
        lines = ("HP 15")
        f.writelines(lines)
        print("Item added")
        f.close()
    elif final == "Back" or final == "back" or final == "3":
        print("Returning")
    else:
        print("Incorrect input")
        HP15()
HP15()    
