def IdeaPad():
    print("Main Specs:")
    print("Processor: 7th Generation Core Intel I3-7020U processor, 2.3 Ghz base speed, 2 cores, 3Mb smart Cache")
    print("Operating System: Preloaded Windows 10 Home, with lifetime validity")
    print("Display: 15.6-inch screen with (1920X1080) full HD display | Anti Glare technology")
    print("Memory and Storage: 4 GB RAM | Storage 1 TB HDD")
    print("Design and battery: Laptop weight 2.2kg | Battery Life: Upto 5.5 hours as per MobileMark 2014")
    print("This genuine Lenovo Laptop comes with 1 year onsite domestic warranty from Lenovo covering manufacturing defects and not covering physical damage. For more details, see Warranty section")
    print("Pre-Installed Software: Windows 10 Home | Inside the box: Laptop, Charger, User Manual")
    print("Ports and Optical drive: 2 USB 3.0 | 1 Type C (USB 3.0) | 1 HDMI | 4-in-1 card reader (SD,SDHC,SDXC,MMC) | Combo audio and microphone jack | Without Optical-Drive | 1 LAN port")
    

    Details = input("Type more for further details: ")
    if Details == "More" or Details == "more":
        print("Brand	Lenovo")
        print("Series	Ideapad 330")
        print("Colour	Onyx Black")
        print("Form Factor	Clamshell")
        print("Item Height	23 Millimeters")
        print("Item Width	26 Centimeters")
        print("Screen Size	15.6 Inches")
        print("Maximum Display Resolution	1920 x 1080 (Full HD)")
        print("Item Weight	2.2 Kg")
        print("Product Dimensions	37.8 x 26 x 2.3 cm")
        print("Batteries:	1 Lithium Polymer batteries required. (included)")
        print("Item model number	81DE01K2IN")
        print("Processor Brand	Intel")
        print("Processor Type	Core i3")
        print("Processor Speed	2.30 GHz")
        print("Processor Count	2")
        print("RAM Size	8 GB")
        print("Memory Technology	DDR4")
        print("Computer Memory Type	DDR4 SDRAM")
        print("Maximum Memory Supported	8 GB")
        print("Hard Drive Size	1024 GB")
        print("Hard Disk Technology	Mechanical Hard Drive")
        print("Hard Drive Interface	Serial ATA")
        print("Speaker Description	2x 1.5W, without mesh")
        print("Graphics Coprocessor	Integrated")
        print("Graphics Card Description	Integrated")
        print("Graphics Card Interface	Integrated")
        print("Connectivity Type	WIFI 1X1 AC+BT4.1")
        print("Number of USB 3.0 Ports	2")
        print("Number of HDMI Ports	1")
        print("Number of Audio-out Ports	1")
        print("Number of Ethernet Ports	1")
        print("Number of Microphone Ports	1")
        print("Optical Drive Type	NO ODD")
        print("Operating System	Windows 10, Home")
        print("Average Battery Life (in hours)	6 Hours")
        print("Lithium Battery Energy Content	30 Watt Hours")
        print("Lithium battery Weight	100 Grams")
        print("Number of Lithium Ion Cells	2")
        print("Included Components	Laptop, Adapter, User Manual")
        print()
        print("                    Price: Rs.47,990                    ")
    
    final = input("1.Buy           2.Add to Cart          3.Back")
    if final == "Buy" or final == "buy" or final == "1" :
        print("Item Purchased")
        print("Returning to Home Screen")
        
    elif final == "Add" or final == "add" or final == "2" :
        f = open("Cart", "w")
        lines = ("Lenovo Ideapad 330")
        f.writelines(lines)
        print("Item added")
        f.close()
    elif final == "Back" or final == "back" or final == "3" :
        print("Returning to Home")
    else:
        print("Incorrect input")
        IdeaPad()

IdeaPad()    
