def Legion():
    print("Main Specs:")
    print("Processor: 8th Generation Core Intel I5-8300H processor, 2.3 Ghz base speed, 4 Ghz max speed, 4 cores, 8Mb Smart Cache")
    print("Operating System: Preloaded Windows 10 Home, with lifetime validity")
    print("Display: 15.6-inch screen with (1920X1080) full HD display | Anti Glare technology | 60 FPS | 60Hz refresh rate")
    print("Memory and Storage : 8 GB RAM with 4GB NVIDIA GTX 1050 Graphics| Storage: 1 TB HDD")
    print("Design and battery: Gaming Laptop | White Backlit keyboard | Laptop weight: 2.3kg | Battery backup: upto 8 hours")
    print("This genuine Lenovo Laptop comes with 1 year onsite domestic warranty from Lenovo covering manufacturing defects and not covering physical damage. For more details, see Warranty section")
    print("Pre-Installed Software: Windows 10 Home | Inside the box: Laptop, Charger, User Manual")
    print("Ports and Optical Drive: 1 HDMI 2.0, 3 USB 3.1, 1 RJ-45(LAN), 1 mini-Display Port, Combo audio and microphone jack|No Optical Drive")
    
    print("                    Price: Rs.61,990                    ")

    Details = input("Type more for further details: ")
    if Details == "More" or Details == "more":
        print("Brand	Lenovo")
        print("Series	Legion Y530")
        print("Colour	Black")
        print("Item Height	25 Millimeters")
        print("Item Width	26.7 Centimeters")
        print("Screen Size	15 Inches")
        print("Maximum Display Resolution	1920 x 1080 (Full HD)")
        print("Item Weight	2.3 Kg")
        print("Product Dimensions	36 x 26.7 x 2.5 cm")
        print("Batteries:	1 Lithium Metal batteries required. (included)")
        print("Item model number	81FV005VIN")
        print("Processor Brand	Intel")
        print("Processor Type	Core i5 8300H")
        print("Processor Speed	4 GHz")
        print("RAM Size	8 GB")
        print("Memory Technology	DDR4")
        print("Hard Drive Size	1024 GB")
        print("Hard Disk Technology	Mechanical Hard Drive")
        print("Speaker Description	2.0W Harman speakers with chamber*2")
        print("Graphics Coprocessor	NVIDIA GeForce GTX 1050")
        print("Graphics Card Ram Size	4 GB")
        print("Connectivity Type	WIFI 2X2 AC+BT4.1")
        print("Number of USB 3.0 Ports	3")
        print("Number of HDMI Ports	1")
        print("Number of Audio-out Ports	1")
        print("Number of Ethernet Ports	1")
        print("Number of Microphone Ports	1")
        print("Optical Drive Type	None")
        print("Operating System	Windows 10, Home")
        print("Lithium Battery Energy Content	52.5 Watt Hours")
        print("Lithium battery Weight	100 Grams")
        print("Number of Lithium Ion Cells	3")
        print("Number of Lithium Metal Cells	2")
        print("Included Components	Laptop, Adapter, User Manual")
        print()
        print("                    Price: Rs.61,990                    ")

    final = input("Buy           Add to Cart          Back")
    if final == "Buy" or final == "buy" or final == "1":
        print("Item Purchased")
        print("Returning to Home Screen")
        
    elif final == "Add" or final == "add" or final == "2" :
        f = open("Cart", "w")
        lines = ("Lenovo Legion Y530")
        f.writelines(lines)
        print("Item added")
        f.close()
    elif final == "Back" or final == "back" or final == "3":
        print("Returning")
    else:
        print("Incorrect input")
        Legion()
Legion()    
